### ISSUE TITLE
impl Display for PackageUrl

### ISSUE THREAD

**Issue by TedDriggs** [althonos/packageurl.rs#2]
Currently, `PackageUrl` has a `ToString` impl but no `Display` impl. This forces a heap allocation to display or serialize the URL.

Looking at the code, it seems that moving to a `Display` impl would be fine, and the blanket `impl<T: Display ToString for T` would make sure the `to_string()` method still worked. Is that doable, or would it break something I'm not seeing?

**Comment by althonos** [comment]
Thanks! I wrote this when I was learning about Rust, so I didn't know all the `std` traits and so on.
