### ISSUE TITLE
Add optional serde support

### ISSUE THREAD

**Issue by TedDriggs** [althonos/packageurl.rs#3]
Right now, `PackageUrl` doesn't implement `serde::Serialize` or `serde::Deserialize`, but does implement `ToString` and `FromStr`. To use `PackageUrl` in a struct that is `#[derive(Serialize)]`, someone needs to add the `#[serde(with = "...")]` attribute.

Proposal: Add a `serde` feature to `packageurl` which lights up `Serialize` and `Deserialize` impls for `PackageUrl`.

**Comment by althonos** [comment]
The new `v0.3.0` release now derives `Serialize` and `Deserialize` when the `serde` feature is enabled. Thanks for the heads-up!
